config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end
  namespace :account do
    resources :orders do
      member do
        post :order_cancel
      end
    end

  end
  resources :items, controller: "cartitems"
  resources :orders do
    member do
      get :pay_with_credit_card
    end
  end
  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end
  resources :products do
    member do
      post :add_to_cart
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM
  belongs_to :user, optional: true
  has_many :items, class_name: "OrderItem", dependent: :destroy
  has_one :info, class_name: "OrderInfo", dependent: :destroy
  accepts_nested_attributes_for :info
  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

  def set_payment_with!(method)
    update_columns(payment_method: method)
  end

  def pay!
    update_columns(is_paid: true)
  end

  def build_item_cache_from_cart(cart)
    cart.cartitems.each do |cart_item|
      item = items.build
      item.product_name = cart_item.product.name
      # item.quantity = cart.cart_item.find_by(product_id: cart_item).quantity
      # item.quantity = cart.find_cart_item(cart_item).quantity
      item.quantity = cart_item.quantity
      item.price = cart_item.product.price
      item.save
    end
  end

  def calculate_total!(cart)
    self.total = cart.total_price
    self.save

  end

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned
    state :user_order_cancelled

    # event :make_payment do
    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid, to: :shipping
    end

    event :deliver do
      transitions from: :shipping, to: :shipped
    end

    event :return_good do
      transitions from: :shipped, to: :good_returned
    end

    event :cancell_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end

end

app/controllers/account/orders_controller.rb
class Account::OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.orders.order("id DESC")
  end

  def order_cancel
    @order = Order.find_by(token: params[:id])
    @order.update(aasm_state: "user_order_cancelled")

    redirect_to :back
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :check_admin!

  def index
    @orders = Order.order("id DESC")
  end

  def show
    @order = Order.find(params[:id])
    @order_info = @order.info
    @order_items = @order.items
  end

  def ship
    @order = Order.find(params[:id])
    @order.ship!
    redirect_to :back
  end

  def shipped
    @order = Order.find(params[:id])
    @order.deliver!
    redirect_to :back
  end

  def cancel
    @order = Order.find(params[:id])
    @order.cancell_order!
    redirect_to :back
  end

  def return
    @order = Order.find(params[:id])
    @order.return_good!
    redirect_to :back
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create

    @order = current_user.orders.build(order_params)

    if @order.save

      @order.build_item_cache_from_cart(current_cart)
      @order.calculate_total!(current_cart)
      current_cart.clean!
      OrderMailer.notify_order_placed(@order).deliver!
      redirect_to order_path(@order.token)
    else
      render "carts/checkout"
    end
  end

  def show
    # @order = Order.find(params[:id])
    @order = Order.find_by(token: params[:id])
    @order_info = @order.info
    @order_items = @order.items
  end

  def pay_with_credit_card
    @order = Order.find_by(token: params[:id])
    @order.set_payment_with!("credit_card")
    # @order.pay!
    @order.make_payment!

    # redirect_to order_path(@order.token), notice: "Success to pay"
    redirect_to account_orders_path, notice: "Success to pay!"
  end

  private

  def order_params
    params.require(:order).permit(info_attributes: [:billing_name,
                                                  :billing_address, :shipping_name, :shipping_address])
  end
end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_state(order)
    t("orders.order_state.#{order.aasm_state}")
  end

  def render_order_paid_state(order)
    if order.is_paid?
      "已付款"
    else
      "未付款"
    end
  end
end

app/views/admin/orders/_state_option.html.erb
<div style= "padding:10px; float:right;">
  <% case order.aasm_state %>
  <% when "order_placed" %>
    <%= link_to("取消訂單", cancel_admin_order_path(order), class: "btn btn-default btn-sm", method: :post) %>
  <% when "paid" %>
    <%= link_to("取消訂單", cancel_admin_order_path(order), class: "btn btn-default btn-sm", method: :post) %>
    <%= link_to("出貨", ship_admin_order_path(order), class: "btn btn-default btn-sm", method: :post) %>
  <% when "shipping" %>
    <%= link_to("設為已出貨", shipped_admin_order_path(order), class: "btn btn-default btn-sm", method: :post) %>
  <% when "shipped" %>
    <%= link_to("退貨", return_admin_order_path(order), class: "btn btn-default btn-sm", method: :post) %>
  <% when "order_cancelled" %>
    <span class="label label-default">訂單已取消</span>
  <% when "user_order_cancelled" %>
    <span class="label label-default"> 使用者取消訂單 </span>
  <% end %>
</div>

app/views/admin/orders/index.html.erb
<h2> 所有訂單列表</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>生成時間</th>
      <th>訂購者</th>
      <th>訂單狀態</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to(order.id, admin_order_path(order)) %></td>
        <td><%= order.created_at.to_s(:long) %></td>
        <td><%= order.user.email %></td>
        <td><%= render_order_state(order) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/orders/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2> 訂單明細(<%= render_order_paid_state(@order) %>)</h2>
    <%= render "admin/orders/state_option", order: @order %>

    <table class="table table-bordered">
      <thead>
        <tr>
          <td width="80%">商品明細</td>
          <td>單價</td>
          <td>數量</td>
        </tr>
      </thead>
      <tbody>
        <% @order_items.each do |order_item| %>
          <tr>
            <td>
              <%= order_item.product_name %>
            </td>
            <td>
              <%= order_item.price %>
            </td>
            <td>
              <%= order_item.quantity %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="total clearfix">
      <span class="pull-right">
        <span> 總計 <%= @order.total %> NTD
        </span>
      </span>
    </div>
    <hr>
    <h2> 寄送資訊</h2>
    <table class="table table-striped table-bordered">
      <tbody>
        <tr>
          <td>
            訂購人
          </td>
        </tr>
        <tr>
          <td>
            <%= @order_info.billing_name %> - <%= @order_info.billing_address %>
          </td>
        </tr>
        <tr>
          <td>
            收件人
          </td>
        </tr>
        <tr>
          <td>
            <%= @order_info.shipping_name %> - <%= @order_info.shipping_address %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>