config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end
  namespace :account do
    resources :orders do
      member do
        post :order_cancel
      end
    end

  end
  resources :items, controller: "cartitems"
  resources :orders do
    member do
      get :pay_with_credit_card
    end
  end
  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end
  resources :products do
    member do
      post :add_to_cart
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cartitems, dependent: :destroy

  def find_cart_item(product)
    cartitems.find_by(product_id: product)
  end

  def clean!
    cartitems.destroy_all
  end

  def total_price
    sum =0
    cartitems.each do |cartitem|
      sum = sum + (cartitem.product.price * cartitem.quantity)
    end
    sum
  end

  
  def total_qty
    cartitems.map{ |x| x.qty }.sum

  end

  def add_product(product)
    existing = cartitems.find_by_product_id( product.id)
    if existing
      existing.qty += 1
      existing.save!
    else
      item = cartitems.build(product_id: product.id, qty: 1)
      item.save!
    end
  end
  #
  # def add_product(product)
  #   existing_item = self.cartitems.find_by_product_id( product.id )
  #   if existing_item
  #     existing_item.qty += 1
  #     existing_item.save!
  #   else
  #     item = self.cartitems.build( :product_id => product.id, :qty => 1 )
  #     item.save!
  #   end
  # end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:ckeckout]

  def index
    @items = current_cart.cartitems
  end

  def clean
    current_cart.clean!
    flash[:warning] = "已清空購物車！！"
    redirect_to carts_path
  end

  def checkout
    @order = current_user.orders.build
    @info = @order.build_info
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end

  
end

app/views/carts/checkout.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>  購物明細</h2>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">
            商品明細
          </th>
          <th>單價</th>
          <th>數量</th>
          <th>計</th>
        </tr>
      </thead>
      <tbody>
        <% current_cart.cartitems.each do |product| %>
          <tr>
            <td>
              <%= link_to(product.product.name, product_path(product.product)) %>
            </td>
            <td>
              <%= product.product.price %>
            </td>
            <td>
              <%= product.quantity %>
            </td>
            <td>
              <%= product.product.price * product.quantity %> NTD
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        總計 <%= render_cart_total_price(current_cart) %> NTD
      </span>
    </div>
    <hr>
    <h2>  訂單資訊</h2>
    <div class="order-form">
      <%= simple_form_for @order do |f| %>
        <%= f.simple_fields_for :info do |c| %>
          <legend>訂購人</legend>
          <div class="form-group col-lg-6">
            <%= c.input :billing_name %>
          </div>
          <div class="form-group col-lg-6">
            <%= c.input :billing_address %>
          </div>

          <legend> 收貨人</legend>
          <div class="form-group col-lg-6">
            <%= c.input :shipping_name %>
          </div>
          <div class="form-group col-lg-6">
            <%= c.input :shipping_address %>
          </div>
        <% end %>
        <div class="checkout">
          <%= f.submit "生成訂單！", class: "btn btn-lg btn-danger pull-right", data:{ disable_with: "Submitting...."} %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to("清空購物車", clean_carts_path, method: :delete, class: "pull-right", style: "text-decoration: underlinke;", data: {confirm: "你確定要清空購物車嗎？？"}) %>
    <h2> Your Shoopin Cart</h2>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">商品資訊</th>
          <th>單價</th>
          <th>數量</th>

          <th>操作選項</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |product| %>
          <tr>
            <td>
              <%= link_to(product_path(product.product_id)) do %>
                <% if product.product.image_url.url.present? %>
                  <%= image_tag(product.product.image_url.medium.url, class: "thumbnail") %>
                <% else %>
                  <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to(product.product.name, product_path(product.product_id)) %>
            </td>
            <td>
            <%= product.product.price %>
            </td>
            <td>
              <p>剩餘數量： <%= product.product.qty %> </p>
              <% itemm = current_cart.cartitems.find_by(id: product) %>
              <%= simple_form_for itemm, url: item_path(product) do |f| %>
                <%= f.select :quantity, 1..product.product.qty %>
                <%= f.submit "更新", data:{ disable_with: "Submiting..."} %>
              <% end %>
            </td>

            <td>
              <%= link_to(item_path(product), method: :delete) do %>
                <i class="icon-trash icon-2x">  </i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <div class="total clearfix">
      <span class="pull-right">
        <span> 總計 <%= render_cart_total_price(current_cart) %> NTD</span>
      </span>
    </div>
    <hr>
    <div class="checkout clearfix">
      <%= link_to("確認結帳", checkout_carts_path, method: :post, class: "btn btn-lg btn-danger pull-right") %>
    </div>
  </div>
</div>