config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end
  namespace :account do
    resources :orders do
      member do
        post :order_cancel
      end
    end

  end
  resources :items, controller: "cartitems"
  resources :orders do
    member do
      get :pay_with_credit_card
    end
  end
  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end
  resources :products do
    member do
      post :add_to_cart
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image_url, ImageUploader
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :check_admin!

  def index
    @products = Product.all
  end
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end

  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path

  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :description, :qty, :image_url)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def add_to_cart
    @product = Product.find(params[:id])
    current_cart.add_product(@product)
    redirect_to :back
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<%= simple_form_for @product, url: admin_product_path do |f| %>
  <div class="form-group">
    <%= f.input :name  , label: "產品名稱", input_html:{class: "form-control"} %>
    <%= f.input :description  , label: "描述", input_html:{class: "form-control"} %>

    <%= f.input :qty , label: '數量', input_html:{class: "form-control" ,} %>
    <%= f.input :price , label: "價格", input_html:{class: "form-control"} %>
    <% if @product.image_url.url.present? %>
        <%= image_tag(@product.image_url.medium.url) %>
    <% end %>
    <%= f.input :image_url, as: :file %>

  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting....."} %>

<% end %>

app/views/admin/products/index.html.erb
<h1>Admin Products list</h1>
<%= link_to("新增產品", new_admin_product_path, class: "btn btn-primary pull-right") %>
<br><br><br>
<table class="table">


  <thead>
    <th>產品照片</th>
    <th>產品名稱</th>
    <th>產品價格</th>
    <th>產品數量</th>
    <th>Edit</th>
    <th>Delete</th>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td>
        <% if product.image_url.url.present? %>
          <%= image_tag(product.image_url.medium.url) %>
        <% else %>
          <%= image_tag("http://loremflickr.com/100/100") %>
        <% end %>
      </td>
      <td>
        <%= product.name %>
      </td>
      <td>
        $<%= product.price %>
      </td>
      <td>
        <%= product.qty %>
      </td>
      <td>
        <%= link_to("Edit",edit_admin_product_path(product), class: "btn btn-info") %>
      </td>
      <td>
        <%= link_to("Delete", admin_product_path(product), method: :delete, data:{confirm: " 哩咖丁？？？"}, class: "btn btn-warning") %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<%= simple_form_for @product, url: admin_products_path do |f| %>
  <div class="form-group">
    <%= f.input :name  , label: "產品名稱", input_html:{class: "form-control"} %>
    <%= f.input :description  , label: "描述", input_html:{class: "form-control"} %>

    <%= f.input :qty , label: '數量', input_html:{class: "form-control" ,} %>
    <%= f.input :price , label: "價格", input_html:{class: "form-control"} %>
    <%= f.input :image_url, as: :file %>

  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting....."} %>

<% end %>