config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end
  namespace :account do
    resources :orders do
      member do
        post :order_cancel
      end
    end

  end
  resources :items, controller: "cartitems"
  resources :orders do
    member do
      get :pay_with_credit_card
    end
  end
  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end
  resources :products do
    member do
      post :add_to_cart
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image_url, ImageUploader
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :check_admin!

  def index
    @products = Product.all
  end
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end

  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path

  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :description, :qty, :image_url)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def add_to_cart
    @product = Product.find(params[:id])
    current_cart.add_product(@product)
    redirect_to :back
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<h1><%= t( "product_list" ) %></h1>

<p>購物車有<span id="cart-total"> <%= current_cart.total_qty %> </span>個商品</p>

<hr>
<div class="row">
  <% @products.each do |product| %>
    <div class="col-xs-6 col-md-3">
      <%= link_to product_path(product) do %>
        <% if product.image_url.url.present? %>
          <%= image_tag(product.image_url, width: 200) %>
        <% else %>
          <%= image_tag("http://loremflickr.com/200/200") %>
        <% end %>
      <% end %>
      <p ><br>
      <%= product.name %> $ <%= product.price %>
      </p>
      <p>
        <%= link_to "加入購物車", add_to_cart_product_path(product), :method => :post, :class => "btn btn-primary"%>
      </p>
    </div>
  <% end %>
</div>